const quotes = [
    "The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Your time is limited, so don't waste it living someone else's life. – Steve Jobs",
    "If life were predictable it would cease to be life, and be without flavor. – Eleanor Roosevelt",
    "If you look at what you have in life, you'll always have more. –Oprah Winfrey",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. –James Cameron",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "The only true wisdom is in knowing you know nothing. – Socrates",
    "In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
    "Life is really simple, but we insist on making it complicated. – Confucius",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. – Buddha",
    "It is not length of life, but depth of life. – Ralph Waldo Emerson",
    "Happiness is not something ready-made. It comes from your own actions. – Dalai Lama",
    "Life isn't about finding yourself. Life is about creating yourself. – George Bernard Shaw",
    "The mind is everything. What you think you become. – Buddha",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill",
    "Do not take life too seriously. You will never get out of it alive. – Elbert Hubbard",
    "Turn your wounds into wisdom. – Oprah Winfrey",
    "Wisdom is the reward you get for a lifetime of listening when you'd have preferred to talk. – Doug Larson",
    "Knowing yourself is the beginning of all wisdom. – Aristotle",
    "The only journey is the one within. – Rainer Maria Rilke",
    "The fool doth think he is wise, but the wise man knows himself to be a fool. – William Shakespeare",
    "A journey of a thousand miles begins with a single step. – Lao Tzu",
    "It is not how old you are, but how you are old. – Jules Renard",
    "A wise man will make more opportunities than he finds. – Francis Bacon",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela",
    "Change your thoughts and you change your world. – Norman Vincent Peale",
    "The unexamined life is not worth living. – Socrates",
    "Everything has beauty, but not everyone sees it. – Confucius",
    "The only thing we have to fear is fear itself. – Franklin D. Roosevelt",
    "An eye for an eye only ends up making the whole world blind. – Mahatma Gandhi",
    "Imagination is more important than knowledge. – Albert Einstein",
    "It's not what happens to you, but how you react to it that matters. – Epictetus",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "He who has a why to live can bear almost any how. – Friedrich Nietzsche",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "We don't see things as they are, we see them as we are. – Anaïs Nin",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
    "Be yourself; everyone else is already taken. – Oscar Wilde",
    "I think, therefore I am. – René Descartes",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "Wisdom begins in wonder. – Socrates",
    "The mind is not a vessel to be filled, but a fire to be kindled. – Plutarch",
    "A wise man can learn more from a foolish question than a fool can learn from a wise answer. – Bruce Lee",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "A little knowledge that acts is worth infinitely more than much knowledge that is idle. – Khalil Gibran",
    "It is better to remain silent and be thought a fool than to speak and remove all doubt. – Abraham Lincoln",
    "The wise man does not lay up his own treasures. The more he gives to others, the more he has for his own. – Lao Tzu",
    "Wisdom is not a product of schooling but of the lifelong attempt to acquire it. – Albert Einstein",
    "Action is the foundational key to all success. – Pablo Picasso",
    "Patience is bitter, but its fruit is sweet. – Aristotle",
    "The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi",
    "To avoid criticism, do nothing, say nothing, and be nothing. – Elbert Hubbard",
    "It does not matter how slowly you go, as long as you do not stop. – Confucius",
    "Success is how high you bounce when you hit bottom. – George S. Patton",
    "The journey is the reward. – Chinese Proverb",
    "Life is about making an impact, not making an income. – Kevin Kruse",
    "Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer",
    "The invariable mark of wisdom is to see the miraculous in the common. – Ralph Waldo Emerson",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. – Aristotle",
    "What we achieve inwardly will change outer reality. – Plutarch",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "There is no greater agony than bearing an untold story inside you. – Maya Angelou",
    "Our lives begin to end the day we become silent about things that matter. – Martin Luther King Jr.",
    "Education is the most powerful weapon which you can use to change the world. – Nelson Mandela",
    "Honesty is the first chapter in the book of wisdom. – Thomas Jefferson",
    "Knowledge speaks, but wisdom listens. – Jimi Hendrix",
    "He who learns but does not think, is lost! He who thinks but does not learn is in great danger. – Confucius",
    "The measure of intelligence is the ability to change. – Albert Einstein",
    "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. – Charles Darwin",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. – Ralph Waldo Emerson",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "Be the change that you wish to see in the world. – Mahatma Gandhi",
    "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power. – Lao Tzu",
    "The greatest mistake you can make in life is to continually fear you will make one. – Elbert Hubbard",
    "Wisdom consists of the anticipation of consequences. – Norman Cousins",
    "You only live once, but if you do it right, once is enough. – Mae West",
    "The more you praise and celebrate your life, the more there is in life to celebrate. – Oprah Winfrey",
    "It is not what we have in life, but who we have in our life that matters. – Margaret Laurence",
    "He who has a why to live can bear almost any how. – Viktor Frankl",
    "The two most important days in your life are the day you are born and the day you find out why. – Mark Twain",
    "The only real mistake is the one from which we learn nothing. – Henry Ford",
    "Happiness depends upon ourselves. – Aristotle",
    "You cannot find peace by avoiding life. – Virginia Woolf",
    "The best and most beautiful things in the world cannot be seen or even touched – they must be felt with the heart. – Helen Keller",
    "The more I read, the more I acquire, the more certain I am that I know nothing. – Voltaire",
    "Do what is right, not what is easy nor what is popular. – Roy T. Bennett",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "The man who removes a mountain begins by carrying away small stones. – Confucius",
    "There is more to life than increasing its speed. – Mahatma Gandhi",
    "It's not the years in your life that count. It’s the life in your years. – Abraham Lincoln",
    "The most courageous act is still to think for yourself. Aloud. – Coco Chanel",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
    "Not everything that is faced can be changed, but nothing can be changed until it is faced. – James Baldwin",
    "A wise man never knows all, only fools know everything. – African Proverb",
    "It’s better to be a lion for a day than a sheep all your life. – Elizabeth Kenny",
    "He who fears he will suffer, already suffers because he fears. – Michel de Montaigne",
    "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.' – Mary Anne Radmacher",
    "Do what you feel in your heart to be right – for you’ll be criticized anyway. – Eleanor Roosevelt",
    "Mistakes are the portals of discovery. – James Joyce",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "Life is too important to be taken seriously. – Oscar Wilde",
    "Failure is success in progress. – Albert Einstein",
    "A day without laughter is a day wasted. – Charlie Chaplin",
    "An unexamined life is not worth living. – Socrates",
    "You can't use up creativity. The more you use, the more you have. – Maya Angelou",
    "A fool thinks himself to be wise, but a wise man knows himself to be a fool. – William Shakespeare",
    "Fall seven times, stand up eight. – Japanese Proverb",
    "Don't judge each day by the harvest you reap but by the seeds that you plant. – Robert Louis Stevenson",
    "The secret of getting ahead is getting started. – Mark Twain",
    "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "A smooth sea never made a skilled sailor. – Franklin D. Roosevelt",
    "Happiness is not by chance, but by choice. – Jim Rohn",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "Strive not to be a success, but rather to be of value. – Albert Einstein",
    "Do one thing every day that scares you. – Eleanor Roosevelt",
    "We are all in the gutter, but some of us are looking at the stars. – Oscar Wilde",
    "Perfection is not attainable, but if we chase perfection, we can catch excellence. – Vince Lombardi",
    "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
"Opportunities don’t happen. You create them. – Chris Grosser",
"You must be the change you wish to see in the world. – Mahatma Gandhi,",
"Do not follow where the path may lead. Go instead where there is no path and leave a trail. – Ralph Waldo Emerson,",
"Great things never come from comfort zones. – Anonymous,",
"There is no substitute for hard work. – Thomas Edison,",
"Don't wait. The time will never be just right. – Napoleon Hill,",
"The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson,",
"I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison,",
"Dream big and dare to fail. – Norman Vaughan,",
"Everything you can imagine is real. – Pablo Picasso,",
"Go confidently in the direction of your dreams. Live the life you have imagined. – Henry David Thoreau,",
"Happiness is not something ready made. It comes from your own actions. – Dalai Lama,",
"A person who never made a mistake never tried anything new. – Albert Einstein,",
"The purpose of our lives is to be happy. – Dalai Lama,",
"Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis,",
"If you want to fly, give up everything that weighs you down. – Buddha,",
"Success is the sum of small efforts, repeated day in and day out. – Robert Collier,",
"The only way to achieve the impossible is to believe it is possible. – Charles Kingsleigh,",
"Keep going. Be all in. – Bryan Hutchinson,",
"Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt,",
"Don't watch the clock; do what it does. Keep going. – Sam Levenson,",
"The harder the conflict, the greater the triumph. – George Washington,",
"Dream as if you’ll live forever, live as if you’ll die today. – James Dean,",
"Success is not in what you have, but who you are. – Bo Bennett,",
"Everything you've ever wanted is on the other side of fear. – George Addair,",
"To be the best, you must be able to handle the worst. – Wilson Kanadi,",
"The successful warrior is the average man, with laser-like focus. – Bruce Lee,",
"Success is getting what you want, happiness is wanting what you get. – W.P. Kinsella,",
"The way to achieve your own success is to be willing to help somebody else get it first. – Iyanla Vanzant,",
"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson,",
"People who are crazy enough to think they can change the world, are the ones who do. – Rob Siltanen,",
"It is our choices that show what we truly are, far more than our abilities. – J.K. Rowling,",
"The harder I work, the luckier I get. – Samuel Goldwyn,",
"Doubt kills more dreams than failure ever will. – Suzy Kassem,",
"Your limitation—it’s only your imagination. – Anonymous,",
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt,",
"The only place where success comes before work is in the dictionary. – Vidal Sassoon,",
"Success is liking yourself, liking what you do, and liking how you do it. – Maya Angelou,",
"Don’t wish it were easier, wish you were better. – Jim Rohn,",
"What we think, we become. – Buddha,",
"Don’t count the days, make the days count. – Muhammad Ali,",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt,",
"Small deeds done are better than great deeds planned. – Peter Marshall,",
"What would you do if you weren’t afraid? – Sheryl Sandberg,",
"Don’t let the fear of losing be greater than the excitement of winning. – Robert Kiyosaki,",
"Don't limit your challenges. Challenge your limits. – Anonymous,",
"All progress takes place outside the comfort zone. – Michael John Bobak,",
"Dream bigger. Do bigger. – Anonymous,",
"I never dreamed about success, I worked for it. – Estée Lauder,",
"Our greatest glory is not in never falling, but in rising every time we fall. – Confucius,",
"It is never too late to be what you might have been. – George Eliot,",
"You can’t have a million-dollar dream with a minimum-wage work ethic. – Stephen C. Hogan,",
"Motivation is what gets you started. Habit is what keeps you going. – Jim Ryun,",
"If opportunity doesn’t knock, build a door. – Milton Berle,",
"You can either experience the pain of discipline or the pain of regret. The choice is yours. – Anonymous,",
"Impossible is just an opinion. – Paulo Coelho,",
"Your past does not equal your future. – Tony Robbins,",
"Life is short, and it is here to be lived. – Kate Winslet,",
"Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett,",
"Courage is one step ahead of fear. – Coleman Young,",
"Work hard in silence, let your success be the noise. – Frank Ocean,",
"Hard times don't create heroes. It is during the hard times when the 'hero' within us is revealed. – Bob Riley,",
"Success is nothing more than a few simple disciplines, practiced every day. – Jim Rohn,",
"The difference between who you are and who you want to be is what you do. – Anonymous,",
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar,",
"Be so good they can’t ignore you. – Steve Martin,",
"Do something today that your future self will thank you for. – Anonymous,",
"Success is what happens after you have survived all of your disappointments. – Anonymous,",
"The only difference between ordinary and extraordinary is that little extra. – Jimmy Johnson,",
"Don’t wait for opportunity. Create it. – Anonymous,",
"Successful people do what unsuccessful people are not willing to do. Don’t wish it were easier; wish you were better. – Jim Rohn,",
"Success is the sum of small efforts, repeated day in and day out. – Robert Collier,",
"The road to success and the road to failure are almost exactly the same. – Colin R. Davis,",
"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett,",
"Live as if you were to die tomorrow. Learn as if you were to live forever. – Mahatma Gandhi,",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller,",
"You can do anything, but not everything. – David Allen,",
"Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston Churchill,",
"Never give in except to convictions of honor and good sense. – Winston Churchill,",
"Fortune favors the brave. – Virgil,",
"Everything you’ve ever wanted is on the other side of fear. – George Addair,",
"Success is how high you bounce when you hit bottom. – George S. Patton,",
"Do what you can, with what you have, where you are. – Theodore Roosevelt,",


];

function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
}

document.addEventListener('DOMContentLoaded', () => {
    const quoteText = document.getElementById('quote');
    const authorText = document.getElementById('author');
    const newQuoteButton = document.getElementById('new-quote');

    function displayNewQuote() {
        const randomQuote = getRandomQuote();
        const [quote, author] = randomQuote.split(' –');
        quoteText.textContent = quote;
        authorText.textContent = `- ${author}`;
    }

    newQuoteButton.addEventListener('click', displayNewQuote);


    displayNewQuote();
});
